Add database
IAmA1ex/java-filmorate pull request #10
Opened 2024-04-27 23:59 UTC by IAmA1ex

2024-04-29 13:26 UTC, z8q requested changes

2024-04-29 13:26 UTC, z8q commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS users (
Нужно разделить этот файлик на schema.sql и data.sql.
В schema - создание таблиц
В data - заполнение данными

2024-04-29 13:26 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film filmFromRequest) throws NotFoundException, BadRequestException {
Допускается добавление дублей фильмов. Можно сделать проверку некоторых полей на уникальность

2024-04-29 13:26 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film filmFromRequest) throws NotFoundException, BadRequestException {
С пользователями такая проверка есть, но возвращается сообщение с ошибкой

```JSON
{
	"error": "PreparedStatementCallback; SQL [INSERT INTO users (email, login, username, birthday) VALUES (?, ?, ?, ?); ]; Unique index or primary key violation: \"PUBLIC.CONSTRAINT_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'bob@yandex.ru' )\"; SQL statement:\nINSERT INTO users (email, login, username, birthday) VALUES (?, ?, ?, ?) [23505-220]; nested exception is org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: \"PUBLIC.CONSTRAINT_INDEX_4 ON PUBLIC.USERS(EMAIL NULLS FIRST) VALUES ( /* 1 */ 'bob@yandex.ru' )\"; SQL statement:\nINSERT INTO users (email, login, username, birthday) VALUES (?, ?, ?, ?) [23505-220]"
}
```

Внутренние sql запросы лучше не возвращать. Вместо этого можно в ExceptionHandler делать обработку и возвращать описание ошибки

2024-04-29 13:26 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +    public User addUser(User userFromRequest) throws NotFoundException {
Еще если отправляем на сохранение пустое поле name, его надо заполнять значением из login.

При update тоже может приходить пустой name, нужно предусмотреть

2024-04-29 13:26 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public UserFilmResponse setLike(@PathVariable("id") Integer filmId,
Если будет приходить запрос с лайком на несуществующий фильм или от несуществующего пользователя, будет приходить ошибка 500 - на стороне сервера.
Нужно присылать 4** - ошибка на стороне клиента, можно возвращать причину ошибки

2024-04-29 13:26 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public UserFilmResponse setLike(@PathVariable("id") Integer filmId,
При повторном лайке можно возвращать сообщение, что лайк уже был поставлен

2024-04-29 15:02 UTC, IAmA1ex commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS users (
Я разделял, но к сожалению schema.sql почему-то не исполняется

2024-04-29 15:39 UTC, IAmA1ex commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film filmFromRequest) throws NotFoundException, BadRequestException {
Одинаковый фильм теперь при совпадении названия и даты выхода. Ответ:
`{
    "error": "Film already exists."
}`

2024-04-29 18:56 UTC, IAmA1ex commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +    public Film addFilm(Film filmFromRequest) throws NotFoundException, BadRequestException {
Сделал проверку на наличие объекта в бд. При одинаковых названиях и датах выхода фильмы считаются одинаковыми. При одинаковых имейлах или логинах пользователи считаются одинаковыми

2024-04-29 19:22 UTC, IAmA1ex commented on src/main/resources/data.sql
> +CREATE TABLE IF NOT EXISTS users (
Делал. У меня почему-то не работало. Не знаю почему. Сейчас заработало

2024-04-29 19:54 UTC, IAmA1ex commented
Я сделал то, что ты просил, но проблема в том что когда прогоняются тесты в папке жанров имеется такая особенность, что фильмы одинаковые отправляются на создание перед тестом самим, из-за этого тесты не проходят так как проверяемые поля не меняются. Можешь сам проверить если отправить запросы с нормальными данными или сбрасывать бд, то все работать будет 

На первом скриншоте видено какой я фильм создал запросом а на втором видно какой я получил 

<img width="1680" alt="Снимок экрана 2024-04-29 в 22 51 21" src="https://github.com/IAmA1ex/java-filmorate/assets/147760167/0ef5e1fe-6c2d-4a31-b683-a0ddb89065b0">
<img width="1680" alt="Снимок экрана 2024-04-29 в 22 51 31" src="https://github.com/IAmA1ex/java-filmorate/assets/147760167/c11834f7-b891-4efa-98f2-d138d64a5abb">

2024-04-30 13:34 UTC, z8q approved these changes

2024-05-09 12:46 UTC, merged