Sprint 9 feature: User, Film, UserController, FilmController
IAmA1ex/java-filmorate pull request #5
Opened 2024-03-18 21:38 UTC by IAmA1ex

2024-03-19 17:41 UTC, z8q requested changes

2024-03-19 17:41 UTC, z8q commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @Birthday
Тут можно применить аннотацию Past

2024-03-20 21:04 UTC, IAmA1ex commented on src/main/java/ru/yandex/practicum/filmorate/validation/LoginValidator.java
> +        return !string.contains(" ");
NotBlank же проверяет что строка состоит из " ", а я проверяю на наличие их в строке в принципе. Если не делать такую проверку то передается null и ошибка NullPointerException

2024-03-21 18:18 UTC, z8q approved these changes

2024-03-21 18:18 UTC, z8q commented on pom.xml
> +			<groupId>org.zalando</groupId>
В этой зависимости нет необходимости.
И кажется ее не используем,
в applicatioon.properties закомментировано:
#logging.level.org.zalando.logbook=TRACE

2024-03-21 19:51 UTC, IAmA1ex commented on pom.xml
> +			<groupId>org.zalando</groupId>
Да, я передумал ее использовать и забыл убрать

2024-03-23 23:48 UTC, merged